/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package queuing;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author jonassimonsen
 */
public class GUI2 extends javax.swing.JFrame {
    ArrayList<Player> personList;
    int counter = 0;

    /**
     * Creates new form GUI2
     */
    public GUI2() {
        initComponents();
    }

    GUI2(ArrayList<Player> personList) {
        initComponents();
        this.jButtonNext.setEnabled(false);
        this.getContentPane().setBackground(Color.orange);
        this.personList = personList;
        jLabelPlayer.setText(personList.get(counter++).getNavn());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDG = new javax.swing.JLabel();
        jLabelDie1 = new javax.swing.JLabel();
        jLabelDie2 = new javax.swing.JLabel();
        jLabelRule = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jButtonRollDice = new javax.swing.JButton();
        jLabelPlayer = new javax.swing.JLabel();
        jLabelInfoPlayer = new javax.swing.JLabel();
        jLabelRule1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelDG.setFont(new java.awt.Font("Lucida Grande", 1, 26)); // NOI18N
        jLabelDG.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/roskilde_logoresize.png"))); // NOI18N
        jLabelDG.setText("Drinking Game");

        jLabelDie1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDie1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dice.gif"))); // NOI18N

        jLabelDie2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDie2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dice.gif"))); // NOI18N

        jLabelRule.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelRule.setText("Rule:");

        jButtonBack.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jButtonNext.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Next.png"))); // NOI18N
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jButtonRollDice.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRollDice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Terning.png"))); // NOI18N
        jButtonRollDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRollDiceActionPerformed(evt);
            }
        });

        jLabelPlayer.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelPlayer.setText("Name");

        jLabelInfoPlayer.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelInfoPlayer.setText("The player is:");

        jLabelRule1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelRule1.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDG, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabelDie1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelDie2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonRollDice, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jLabelPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelInfoPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(125, 125, 125))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRule1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDG, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelDie2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDie1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addComponent(jLabelInfoPlayer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPlayer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRollDice, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabelRule)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRule1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        showNextPlayer();
        this.jButtonRollDice.setEnabled(true);
        this.jButtonNext.setEnabled(false);
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        changeGUI();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonRollDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRollDiceActionPerformed
        startGame();
        this.jButtonRollDice.setEnabled(false);
        this.jButtonNext.setEnabled(true);
        
        
    }//GEN-LAST:event_jButtonRollDiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI2().setVisible(true);
            }
        });
    }
    
    private void changeGUI() {
        GUI play = new GUI();
        play.setVisible(true); 
        this.setVisible(false);
    }
    
    private void startGame() {
        GameEngine game = new GameEngine("Player");
        int[] result = game.playRound();
        
        if (result[0] == 1){    
            ImageIcon iconLogo = new ImageIcon("Images/dice-1.png");
            // In init() method write this code
            jLabelDie1.setIcon(iconLogo);
            //jLabel1.setIcon();
        }
        if (result[0] == 2){
            ImageIcon iconLogo = new ImageIcon("Images/dice-2.png");
            // In init() method write this code
            jLabelDie1.setIcon(iconLogo);
        }
         if (result[0] == 3){
            ImageIcon iconLogo = new ImageIcon("Images/dice-3.png");
            // In init() method write this code
            jLabelDie1.setIcon(iconLogo);
        }
        if (result[0] == 4){
            ImageIcon iconLogo = new ImageIcon("Images/dice-4.png");
            // In init() method write this code
            jLabelDie1.setIcon(iconLogo);
        }
        if (result[0] == 5){
            ImageIcon iconLogo = new ImageIcon("Images/dice-5.png");
            // In init() method write this code
            jLabelDie1.setIcon(iconLogo);
        }
        if (result[0] == 6){
            ImageIcon iconLogo = new ImageIcon("Images/dice-6.png");
            // In init() method write this code
            jLabelDie1.setIcon(iconLogo);
        }
        if (result[1] == 1){
            ImageIcon iconLogo = new ImageIcon("Images/dice-1.png");
            // In init() method write this code
            jLabelDie2.setIcon(iconLogo);
            //jLabel1.setIcon();
        }
        if (result[1] == 2){
            ImageIcon iconLogo = new ImageIcon("Images/dice-2.png");
            // In init() method write this code
            jLabelDie2.setIcon(iconLogo);
        }
        if (result[1] == 3){
            ImageIcon iconLogo = new ImageIcon("Images/dice-3.png");
            // In init() method write this code
            jLabelDie2.setIcon(iconLogo);
        }
        if (result[1] == 4){
            ImageIcon iconLogo = new ImageIcon("Images/dice-4.png");
            // In init() method write this code
            jLabelDie2.setIcon(iconLogo);
        }
        if (result[1] == 5){
            ImageIcon iconLogo = new ImageIcon("Images/dice-5.png");
            // In init() method write this code
            jLabelDie2.setIcon(iconLogo);
        }
        if (result[1] == 6){
            ImageIcon iconLogo = new ImageIcon("Images/dice-6.png");
            // In init() method write this code
            jLabelDie2.setIcon(iconLogo);
        }
            if ((result[0] + result[1]) ==  2) {
            jLabelRule.setText("Rule: Chug your beer.");
            jLabelRule1.setText(" ");
        }
        
            else if ((result[0] + result[1]) ==  3) {
            jLabelRule.setText("Rule: The person to your right drinks.");
            jLabelRule1.setText(" ");
        }
            
            if ((result[0] + result[1]) ==  4) {
            jLabelRule.setText("Rule: Choose a person to chug their beer.");
            jLabelRule1.setText(" ");
        }
            
            if ((result[0] + result[1]) ==  5) {
            jLabelRule.setText("Rule: The person to your left drinks.");
            jLabelRule1.setText(" ");
        }
            
            if ((result[0] + result[1]) ==  6) {
            jLabelRule.setText("Rule: Give a complement to a stranger.");
            jLabelRule1.setText(" ");
        }
            
            if ((result[0] + result[1]) ==  7) {
            jLabelRule.setText("Rule: Touch your nose - the last one drinks.");
            jLabelRule1.setText(" ");
        }
            if ((result[0] + result[1]) ==  8) {
            jLabelRule.setText("Rule: Everyone excepts the roller to drink.");
            jLabelRule1.setText(" ");
        }
            
            if ((result[0] + result[1]) ==  9) {
            jLabelRule.setText("Rule: Waterfall.");
            jLabelRule1.setText(" ");
        }
            
            if ((result[0] + result[1]) ==  10) {
            jLabelRule.setText("Rule: Give a highfive to a stranger.");
            jLabelRule1.setText(" ");
        }
            
            if ((result[0] + result[1]) ==  11) {
            jLabelRule.setText("Rule: Tell a joke.");
            jLabelRule1.setText(" ");
        }
            
            if ((result[0] + result[1]) ==  12) {
            jLabelRule.setText("Rule: Everyone cheers while screamming"); 
            jLabelRule1.setText("         Roskilde and drinks afterwards.");
            
        }           
    }

    private void showNextPlayer() {
    jLabelPlayer.setText(personList.get(counter++).getNavn());
        
    if (counter >= personList.size()) {
        counter = 0;
    }
}
        
        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonRollDice;
    private javax.swing.JLabel jLabelDG;
    private javax.swing.JLabel jLabelDie1;
    private javax.swing.JLabel jLabelDie2;
    private javax.swing.JLabel jLabelInfoPlayer;
    private javax.swing.JLabel jLabelPlayer;
    private javax.swing.JLabel jLabelRule;
    private javax.swing.JLabel jLabelRule1;
    // End of variables declaration//GEN-END:variables
}